/// Flutter icons EmptyPicture
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EmptyPicture
///      fonts:
///       - asset: fonts/EmptyPicture.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EmptyPicture {
  EmptyPicture._();

  static const _kFontFam = 'EmptyPicture';

  static const IconData empty_picture = const IconData(0xe800, fontFamily: _kFontFam);
}
