/// Flutter icons NavigationIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavigationIcon
///      fonts:
///       - asset: fonts/NavigationIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavigationIcon {
  NavigationIcon._();

  static const _kFontFam = 'NavigationIcon';

  static const IconData back = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData next = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xe804, fontFamily: _kFontFam);
}
