/// Flutter icons SocialMediaIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialMediaIcon
///      fonts:
///       - asset: fonts/SocialMediaIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SocialMediaIcon {
  SocialMediaIcon._();

  static const _kFontFam = 'SocialMediaIcon';

  static const IconData facebook = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xe802, fontFamily: _kFontFam);
}
